# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hdd.client.detection_pb2 as detection__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectionAndDescriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBoundingBoxes = channel.stream_unary(
                '/DetectionAndDescription/GetBoundingBoxes',
                request_serializer=detection__pb2.DetectionRequest.SerializeToString,
                response_deserializer=detection__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.GetDescription = channel.stream_unary(
                '/DetectionAndDescription/GetDescription',
                request_serializer=detection__pb2.DescriptionRequest.SerializeToString,
                response_deserializer=detection__pb2.DescriptionResponse.FromString,
                _registered_method=True)


class DetectionAndDescriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetBoundingBoxes(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDescription(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectionAndDescriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBoundingBoxes': grpc.stream_unary_rpc_method_handler(
                    servicer.GetBoundingBoxes,
                    request_deserializer=detection__pb2.DetectionRequest.FromString,
                    response_serializer=detection__pb2.DetectionResponse.SerializeToString,
            ),
            'GetDescription': grpc.stream_unary_rpc_method_handler(
                    servicer.GetDescription,
                    request_deserializer=detection__pb2.DescriptionRequest.FromString,
                    response_serializer=detection__pb2.DescriptionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DetectionAndDescription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DetectionAndDescription', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DetectionAndDescription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetBoundingBoxes(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/DetectionAndDescription/GetBoundingBoxes',
            detection__pb2.DetectionRequest.SerializeToString,
            detection__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDescription(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/DetectionAndDescription/GetDescription',
            detection__pb2.DescriptionRequest.SerializeToString,
            detection__pb2.DescriptionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
